### ISSUE TITLE
グラフの範囲変更

### ISSUE THREAD

**Issue by susatthi** [susatthi/flutter-apps#130]
## 関連する Issue

- #160 

## 内容

- 週（対応済み）
- 1ヶ月
- 3ヶ月
- 1年

**Comment by sukekyo-net** [comment]
対応してみますー

**Comment by sukekyo-net** [comment]
ある程度動いているものの、まだ触りたい部分はあるので、ブランチのみpushしておきます。
### やりたいこと
- グラフを切り替えた時にX軸のラベルも切り替えているが、切り替える際に一瞬ごちゃつくため修正したい。
- 3ヶ月表示 の際にX軸のラベルに月も表示したいが、ページ切り替え時に連動出来ていない。ひとまず日のみとしてます。
- ダミーデータの範囲を広げて、細かい部分の動作確認をしたい。
- データを遡っていると、今日に戻ってくるのが大変なので、ジャンプできるボタンを用意したい

### やる予定がないこと
- 切り替えた表示範囲設定の保存
  - 切り替えは一時的な用途と考えているので、設定値では持たせていません。大手証券会社のチャートの切り替えも一時的のようだったので。

**Comment by susatthi** [comment]
>- グラフを切り替えた時にX軸のラベルも切り替えているが、切り替える際に一瞬ごちゃつくため修正したい。
>- 3ヶ月表示 の際にX軸のラベルに月も表示したいが、ページ切り替え時に連動出来ていない。ひとまず日のみとしてます。

上記はもし解決出来なかったら別Issueで私が取り組んでもOKです！

>- ダミーデータの範囲を広げて、細かい部分の動作確認をしたい。

ダミーデータ適当に修正してもＯＫです！

>- データを遡っていると、今日に戻ってくるのが大変なので、ジャンプできるボタンを用意したい

これは別Issueでやりたいです！

>- 切り替えた表示範囲設定の保存
  - 切り替えは一時的な用途と考えているので、設定値では持たせていません。大手証券会社のチャートの切り替えも一時的のようだったので。 

無しでOKです！
