### ISSUE TITLE
ピークフロー入力最小値と最大値のデフォルト値を見直す

### ISSUE THREAD

**Issue by susatthi** [susatthi/flutter-apps#197]
## 関連する Issue

- #196 

## 内容

#182 により、最小値と最大値が変更できるようになったため、デフォルトをより大きくしても問題無くなった。
このIssueでは次の対応をする

- ピークフロー最小値を50から0に変更
- ピークフロー最大値を800から900に変更

#196 から引用
-  [ピークフローメーター活用 ガイドブック](https://www.erca.go.jp/yobou/pamphlet/form/03/pdf/bp025.pdf) の おもなピークフローメーター一覧 によると、小児の下限が30、成人の上限が880 のものもあるため、もう少し範囲を広げても良いかもしれません

## 目的

- 使い勝手向上

**Comment by sukekyo-net** [comment]
プリセットの値も調整したかったので対応します。
