### ISSUE TITLE
チャートの当日にすぐに移動したい

### ISSUE THREAD

**Issue by susatthi** [susatthi/flutter-apps#235]
## 関連する Issue

- #234 「やらないこと」を参照

## 内容

チャートの左右フリックで過去に遡ってしまうと、当日のチャートに戻るのがとても大変。簡単に戻る方法を提供したい。具体的な方法は決まっていないので検討してほしい。

## 目的

- 使い勝手向上

**Comment by sukekyo-net** [comment]
対応します！
